/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Advance = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'labourId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'amount' : IDL.Float64,
  'contractId' : IDL.Nat,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'columnType' : IDL.Text,
  'value' : IDL.Text,
  'labourId' : IDL.Nat,
  'meshColumnId' : IDL.Nat,
  'contractId' : IDL.Nat,
});
export const Contract = IDL.Record({
  'id' : IDL.Nat,
  'settled' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'machineExp' : IDL.Float64,
  'bedAmount' : IDL.Float64,
  'paperAmount' : IDL.Float64,
  'meshAmount' : IDL.Float64,
  'contractAmount' : IDL.Float64,
  'multiplierValue' : IDL.Float64,
});
export const Labour = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const MeshColumn = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'position' : IDL.Nat,
  'contractId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createAdvance' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text],
      [Advance],
      [],
    ),
  'createAttendanceRecord' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [AttendanceRecord],
      [],
    ),
  'createContract' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [Contract],
      [],
    ),
  'createLabour' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Labour], []),
  'createMeshColumn' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [MeshColumn], []),
  'deleteAdvance' : IDL.Func([IDL.Nat], [], []),
  'deleteAttendanceRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteContract' : IDL.Func([IDL.Nat], [], []),
  'deleteLabour' : IDL.Func([IDL.Nat], [], []),
  'deleteMeshColumn' : IDL.Func([IDL.Nat], [], []),
  'getAdvancesByContract' : IDL.Func([IDL.Nat], [IDL.Vec(Advance)], ['query']),
  'getAdvancesByLabour' : IDL.Func([IDL.Nat], [IDL.Vec(Advance)], ['query']),
  'getAttendanceRecordsByContract' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getContractsBySettled' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(Contract)],
      ['query'],
    ),
  'readAdvance' : IDL.Func([IDL.Nat], [Advance], ['query']),
  'readAttendanceRecord' : IDL.Func([IDL.Nat], [AttendanceRecord], ['query']),
  'readContract' : IDL.Func([IDL.Nat], [Contract], ['query']),
  'readLabour' : IDL.Func([IDL.Nat], [Labour], ['query']),
  'readMeshColumn' : IDL.Func([IDL.Nat], [MeshColumn], ['query']),
  'updateAdvance' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text],
      [Advance],
      [],
    ),
  'updateAttendanceRecord' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [AttendanceRecord],
      [],
    ),
  'updateContract' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [Contract],
      [],
    ),
  'updateContractSettled' : IDL.Func([IDL.Nat, IDL.Bool], [Contract], []),
  'updateLabour' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Labour],
      [],
    ),
  'updateMeshColumn' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
      [MeshColumn],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Advance = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'labourId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'amount' : IDL.Float64,
    'contractId' : IDL.Nat,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'columnType' : IDL.Text,
    'value' : IDL.Text,
    'labourId' : IDL.Nat,
    'meshColumnId' : IDL.Nat,
    'contractId' : IDL.Nat,
  });
  const Contract = IDL.Record({
    'id' : IDL.Nat,
    'settled' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'machineExp' : IDL.Float64,
    'bedAmount' : IDL.Float64,
    'paperAmount' : IDL.Float64,
    'meshAmount' : IDL.Float64,
    'contractAmount' : IDL.Float64,
    'multiplierValue' : IDL.Float64,
  });
  const Labour = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MeshColumn = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'position' : IDL.Nat,
    'contractId' : IDL.Nat,
  });
  
  return IDL.Service({
    'createAdvance' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text],
        [Advance],
        [],
      ),
    'createAttendanceRecord' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [AttendanceRecord],
        [],
      ),
    'createContract' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [Contract],
        [],
      ),
    'createLabour' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Labour], []),
    'createMeshColumn' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [MeshColumn],
        [],
      ),
    'deleteAdvance' : IDL.Func([IDL.Nat], [], []),
    'deleteAttendanceRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteContract' : IDL.Func([IDL.Nat], [], []),
    'deleteLabour' : IDL.Func([IDL.Nat], [], []),
    'deleteMeshColumn' : IDL.Func([IDL.Nat], [], []),
    'getAdvancesByContract' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Advance)],
        ['query'],
      ),
    'getAdvancesByLabour' : IDL.Func([IDL.Nat], [IDL.Vec(Advance)], ['query']),
    'getAttendanceRecordsByContract' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getContractsBySettled' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Contract)],
        ['query'],
      ),
    'readAdvance' : IDL.Func([IDL.Nat], [Advance], ['query']),
    'readAttendanceRecord' : IDL.Func([IDL.Nat], [AttendanceRecord], ['query']),
    'readContract' : IDL.Func([IDL.Nat], [Contract], ['query']),
    'readLabour' : IDL.Func([IDL.Nat], [Labour], ['query']),
    'readMeshColumn' : IDL.Func([IDL.Nat], [MeshColumn], ['query']),
    'updateAdvance' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text],
        [Advance],
        [],
      ),
    'updateAttendanceRecord' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [AttendanceRecord],
        [],
      ),
    'updateContract' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [Contract],
        [],
      ),
    'updateContractSettled' : IDL.Func([IDL.Nat, IDL.Bool], [Contract], []),
    'updateLabour' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Labour],
        [],
      ),
    'updateMeshColumn' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [MeshColumn],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };