/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Advance {
  'id' : bigint,
  'note' : string,
  'labourId' : bigint,
  'createdAt' : bigint,
  'amount' : number,
  'contractId' : bigint,
}
export interface AttendanceRecord {
  'id' : bigint,
  'columnType' : string,
  'value' : string,
  'labourId' : bigint,
  'meshColumnId' : bigint,
  'contractId' : bigint,
}
export interface Contract {
  'id' : bigint,
  'settled' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'machineExp' : number,
  'bedAmount' : number,
  'paperAmount' : number,
  'meshAmount' : number,
  'contractAmount' : number,
  'multiplierValue' : number,
}
export interface Labour {
  'id' : bigint,
  'name' : string,
  'notes' : string,
  'phone' : string,
}
export interface MeshColumn {
  'id' : bigint,
  'name' : string,
  'position' : bigint,
  'contractId' : bigint,
}
export interface _SERVICE {
  'createAdvance' : ActorMethod<[bigint, bigint, number, string], Advance>,
  'createAttendanceRecord' : ActorMethod<
    [bigint, bigint, string, bigint, string],
    AttendanceRecord
  >,
  'createContract' : ActorMethod<
    [string, number, number, number, number, number, number],
    Contract
  >,
  'createLabour' : ActorMethod<[string, string, string], Labour>,
  'createMeshColumn' : ActorMethod<[bigint, string, bigint], MeshColumn>,
  'deleteAdvance' : ActorMethod<[bigint], undefined>,
  'deleteAttendanceRecord' : ActorMethod<[bigint], undefined>,
  'deleteContract' : ActorMethod<[bigint], undefined>,
  'deleteLabour' : ActorMethod<[bigint], undefined>,
  'deleteMeshColumn' : ActorMethod<[bigint], undefined>,
  'getAdvancesByContract' : ActorMethod<[bigint], Array<Advance>>,
  'getAdvancesByLabour' : ActorMethod<[bigint], Array<Advance>>,
  'getAttendanceRecordsByContract' : ActorMethod<
    [bigint],
    Array<AttendanceRecord>
  >,
  'getContractsBySettled' : ActorMethod<[boolean], Array<Contract>>,
  'readAdvance' : ActorMethod<[bigint], Advance>,
  'readAttendanceRecord' : ActorMethod<[bigint], AttendanceRecord>,
  'readContract' : ActorMethod<[bigint], Contract>,
  'readLabour' : ActorMethod<[bigint], Labour>,
  'readMeshColumn' : ActorMethod<[bigint], MeshColumn>,
  'updateAdvance' : ActorMethod<
    [bigint, bigint, bigint, number, string],
    Advance
  >,
  'updateAttendanceRecord' : ActorMethod<
    [bigint, bigint, bigint, string, bigint, string],
    AttendanceRecord
  >,
  'updateContract' : ActorMethod<
    [bigint, string, number, number, number, number, number, number],
    Contract
  >,
  'updateContractSettled' : ActorMethod<[bigint, boolean], Contract>,
  'updateLabour' : ActorMethod<[bigint, string, string, string], Labour>,
  'updateMeshColumn' : ActorMethod<
    [bigint, bigint, string, bigint],
    MeshColumn
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];