/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Labour {
    id: bigint;
    name: string;
    notes: string;
    phone: string;
}
export interface MeshColumn {
    id: bigint;
    name: string;
    position: bigint;
    contractId: bigint;
}
export interface Contract {
    id: bigint;
    settled: boolean;
    name: string;
    createdAt: bigint;
    machineExp: number;
    bedAmount: number;
    paperAmount: number;
    meshAmount: number;
    contractAmount: number;
    multiplierValue: number;
}
export interface AttendanceRecord {
    id: bigint;
    columnType: string;
    value: string;
    labourId: bigint;
    meshColumnId: bigint;
    contractId: bigint;
}
export interface Advance {
    id: bigint;
    note: string;
    labourId: bigint;
    createdAt: bigint;
    amount: number;
    contractId: bigint;
}
export interface backendInterface {
    createAdvance(labourId: bigint, contractId: bigint, amount: number, note: string): Promise<Advance>;
    createAttendanceRecord(contractId: bigint, labourId: bigint, columnType: string, meshColumnId: bigint, value: string): Promise<AttendanceRecord>;
    createContract(name: string, multiplierValue: number, contractAmount: number, machineExp: number, bedAmount: number, paperAmount: number, meshAmount: number): Promise<Contract>;
    createLabour(name: string, phone: string, notes: string): Promise<Labour>;
    createMeshColumn(contractId: bigint, name: string, position: bigint): Promise<MeshColumn>;
    deleteAdvance(id: bigint): Promise<void>;
    deleteAttendanceRecord(id: bigint): Promise<void>;
    deleteContract(id: bigint): Promise<void>;
    deleteLabour(id: bigint): Promise<void>;
    deleteMeshColumn(id: bigint): Promise<void>;
    getAdvancesByContract(contractId: bigint): Promise<Array<Advance>>;
    getAdvancesByLabour(labourId: bigint): Promise<Array<Advance>>;
    getAttendanceRecordsByContract(contractId: bigint): Promise<Array<AttendanceRecord>>;
    getContractsBySettled(settled: boolean): Promise<Array<Contract>>;
    readAdvance(id: bigint): Promise<Advance>;
    readAttendanceRecord(id: bigint): Promise<AttendanceRecord>;
    readContract(id: bigint): Promise<Contract>;
    readLabour(id: bigint): Promise<Labour>;
    readMeshColumn(id: bigint): Promise<MeshColumn>;
    updateAdvance(id: bigint, labourId: bigint, contractId: bigint, amount: number, note: string): Promise<Advance>;
    updateAttendanceRecord(id: bigint, contractId: bigint, labourId: bigint, columnType: string, meshColumnId: bigint, value: string): Promise<AttendanceRecord>;
    updateContract(id: bigint, name: string, multiplierValue: number, contractAmount: number, machineExp: number, bedAmount: number, paperAmount: number, meshAmount: number): Promise<Contract>;
    updateContractSettled(contractId: bigint, settled: boolean): Promise<Contract>;
    updateLabour(id: bigint, name: string, phone: string, notes: string): Promise<Labour>;
    updateMeshColumn(id: bigint, contractId: bigint, name: string, position: bigint): Promise<MeshColumn>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAdvance(arg0: bigint, arg1: bigint, arg2: number, arg3: string): Promise<Advance> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdvance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdvance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createAttendanceRecord(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint, arg4: string): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.createAttendanceRecord(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAttendanceRecord(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createContract(arg0: string, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): Promise<Contract> {
        if (this.processError) {
            try {
                const result = await this.actor.createContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createLabour(arg0: string, arg1: string, arg2: string): Promise<Labour> {
        if (this.processError) {
            try {
                const result = await this.actor.createLabour(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLabour(arg0, arg1, arg2);
            return result;
        }
    }
    async createMeshColumn(arg0: bigint, arg1: string, arg2: bigint): Promise<MeshColumn> {
        if (this.processError) {
            try {
                const result = await this.actor.createMeshColumn(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMeshColumn(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAdvance(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdvance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdvance(arg0);
            return result;
        }
    }
    async deleteAttendanceRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAttendanceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAttendanceRecord(arg0);
            return result;
        }
    }
    async deleteContract(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContract(arg0);
            return result;
        }
    }
    async deleteLabour(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLabour(arg0);
            return result;
        }
    }
    async deleteMeshColumn(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeshColumn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeshColumn(arg0);
            return result;
        }
    }
    async getAdvancesByContract(arg0: bigint): Promise<Array<Advance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvancesByContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvancesByContract(arg0);
            return result;
        }
    }
    async getAdvancesByLabour(arg0: bigint): Promise<Array<Advance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvancesByLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvancesByLabour(arg0);
            return result;
        }
    }
    async getAttendanceRecordsByContract(arg0: bigint): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceRecordsByContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceRecordsByContract(arg0);
            return result;
        }
    }
    async getContractsBySettled(arg0: boolean): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractsBySettled(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractsBySettled(arg0);
            return result;
        }
    }
    async readAdvance(arg0: bigint): Promise<Advance> {
        if (this.processError) {
            try {
                const result = await this.actor.readAdvance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readAdvance(arg0);
            return result;
        }
    }
    async readAttendanceRecord(arg0: bigint): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.readAttendanceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readAttendanceRecord(arg0);
            return result;
        }
    }
    async readContract(arg0: bigint): Promise<Contract> {
        if (this.processError) {
            try {
                const result = await this.actor.readContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readContract(arg0);
            return result;
        }
    }
    async readLabour(arg0: bigint): Promise<Labour> {
        if (this.processError) {
            try {
                const result = await this.actor.readLabour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readLabour(arg0);
            return result;
        }
    }
    async readMeshColumn(arg0: bigint): Promise<MeshColumn> {
        if (this.processError) {
            try {
                const result = await this.actor.readMeshColumn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readMeshColumn(arg0);
            return result;
        }
    }
    async updateAdvance(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: string): Promise<Advance> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdvance(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdvance(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateAttendanceRecord(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: bigint, arg5: string): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAttendanceRecord(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAttendanceRecord(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateContract(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): Promise<Contract> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateContractSettled(arg0: bigint, arg1: boolean): Promise<Contract> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContractSettled(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContractSettled(arg0, arg1);
            return result;
        }
    }
    async updateLabour(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Labour> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLabour(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLabour(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateMeshColumn(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint): Promise<MeshColumn> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMeshColumn(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMeshColumn(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
